/* Material */
MATERIAL_THICKNESS = 3;
MACHINE_TOLERANCE = 0.1;

/* Angle */
DEVICE_ANGLE = 45;

/* Dimensions */
WIDTH = 60;
HEIGHT = 50;

SIDE_PANEL_CORNER_RADIUS = 3;


/* Calculated dimensions */
DEPTH = HEIGHT / tan(DEVICE_ANGLE);
HALF_MATERIAL_THICKNESS = MATERIAL_THICKNESS / 2;
HALF_HEIGHT = (HEIGHT / 2) + HALF_MATERIAL_THICKNESS;
HALF_WIDTH = (WIDTH / 2) + HALF_MATERIAL_THICKNESS;
HALF_DEPTH = (DEPTH / 2);
