use <SCAD_Lib/parts/PineA64.scad>

$fn = 16;

MATERIAL_THICKNESS = 3;

PANEL_DIMENSIONS = PineA64BoardDimensions() + [20, 20];
PANEL_CORNER_RAD = 5;

ASSEMBLY_HOLE_CENTRES = PANEL_DIMENSIONS - [12, 12];
ASSEMBLY_HOLE_DIAMETER = 4;

HDD_MOUNTING_HOLE_DIAMETER = 3.2;
