/* Material */
MATERIAL_THICKNESS = 3;
MACHINE_TOLERANCE = 0.1;

/* Tablet */
TABLET_DIMENSIONS = [120, 80, 6];

TABLET_SCREEN_DIMENSIONS = [100, 60];
TABLET_SCREEN_POSITION = [0, 0];

/* Keyboard */
KEYBOARD_DIMENSIONS = [110, 80, 4];

KEYBOARD_KEYS_DIMENSIONS = [90, 50];
KEYBOARD_KEYS_POSITION = [0, 10];

KEYBOARD_TRACKPAD_DIMENSIONS = [30, 20];
KEYBOARD_TRACKPAD_POSITION = [0, -27.5];
